server:
  port: 8502
spring:
  application:
    name: spring-cloud-zipkin
  cloud:
    consul:
       host: 192.168.25.128
       port: 8500
    discovery:
       register: true
       enabled : true
       service-name: spring-cloud-zipkin
       instance-id: ${spring.cloud.consul.discovery.service-name}:${spring.cloud.client.hostname}:${server.port}
    enabled: true

zipkin:
  storage:
     type: mysql
     mysql:
         username: root
         password: 123456
         db: zipkin
         host: 192.168.25.128
         port: 3306

management:
  metrics:
    web:
      server:
        auto-time-requests: false
  endpoints:
      web:
        exposure:
          include: "*"



